name: Create UserScript

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  create-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get style.css
        run: |
          curl https://raw.githubusercontent.com/ronilaukkarinen/mastodon-bird-ui/master/style.css > style.css

      - name: Generate tag name
        run: echo "TAG_NAME=$(date +%F-%H-%M)" >> $GITHUB_ENV

      - name: Create UserScript
        run: |
          echo "// ==UserScript==
          // @name         Mastodon Bird UI
          // @match        https://ieji.de/*
          // @grant        GM_addStyle
          // @version      ${{ env.TAG_NAME }}
          // @author       egecelikci
          // @description  A UserScript that applies the Mastodon Bird UI style to ieji.de
          // @downloadURL  https://github.com/egecelikci/mastodon-bird-ui-userscript/releases/latest/download/mastodon-bird-ui.user.js
          // @updateURL    https://github.com/egecelikci/mastodon-bird-ui-userscript/releases/latest/download/mastodon-bird-ui.user.js
          // ==/UserScript==
          " > mastodon-bird-ui.user.js
          echo "GM_addStyle(\`" >> mastodon-bird-ui.user.js
          cat style.css >> mastodon-bird-ui.user.js
          echo "\`);" >> mastodon-bird-ui.user.js

      - name: Release scripts
        uses: softprops/action-gh-release@v1
        with:
          files: mastodon-bird-ui.user.js
          name: Automatic script generation
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
